### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by Neubulae** [maxvar/mcf-reap#6]
https://pastebin.com/HqPuMsdp

**Comment by maxvar** [comment]
@Neubulae please give me versions of MC, Fabric loader+API and mcf-reap. They are not in the log you provived, so I can't investigate.

**Comment by Neubulae** [comment]
> @Neubulae please give me versions of MC, Fabric loader+API and mcf-reap. They are not in the log you provived, so I can't investigate.

https://pastebin.com/Mf5c6LJn
This log provides more info I guess

**Comment by maxvar** [comment]
@Neubulae can you try with 1.2.1? 
https://www.curseforge.com/minecraft/mc-mods/maxvar-reap-for-fabric/files/2912515
I dropped dependency on fabric-language-kotlin in that version to have less possible conflicts.
Also please check why you now have "`Conflicting versions found for fabric-api-base`" in your log. Maybe you have two versions of fabric-api mods in your installation?

**Comment by Neubulae** [comment]
> @Neubulae can you try with 1.2.1?
> https://www.curseforge.com/minecraft/mc-mods/maxvar-reap-for-fabric/files/2912515
> I dropped dependency on fabric-language-kotlin in that version to have less possible conflicts.
> Also please check why you now have "`Conflicting versions found for fabric-api-base`" in your log. Maybe you have two versions of fabric-api mods in your installation?

I have tried both, but neither of them works

**Comment by maxvar** [comment]
@Neubulae Are you running the mod in a dedicated mc server?

**Comment by Neubulae** [comment]
> @Neubulae Are you running the mod in a dedicated mc server?

Yeah, I thought it was for server side only?

**Comment by maxvar** [comment]
Oops! I did not test it for server-only. It currently works for client.
Thanks to your report, I was able to reproduce the error on a fresh server install.
I'll see how to fix that. Please wait for some time)

**Comment by maxvar** [comment]
@Neubulae could you please help me and check if the 1.2.1 version works in your setup is installed only on the client-side?

**Comment by Neubulae** [comment]
> @Neubulae could you please help me and check if the 1.2.1 version works in your setup is installed only on the client-side?

Yeah it works on clients, but only on singleplayer worlds, I can't use the same functionality in servers(which is trivially obvious)

**Comment by maxvar** [comment]
@Neubulae Thanks, I'll see if I can fix that. I have 0 (zero) experience with server-side aspect of mods though )))

**Comment by maxvar** [comment]
@Neubulae you can check 1.3.0 - "works on my computer")))

**Comment by Neubulae** [comment]
> @Neubulae you can check 1.3.0 - "works on my computer")))

I just took a bath and holy moly, lemme check

**Comment by Neubulae** [comment]
Yeah it worked like a charm! Lovin' it already
